services:
  student:
    container_name: ${API_CONTAINER_NAME_STUDENT}
    build:
      context: student
      dockerfile: Dockerfile.student
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_HOST=${SERVER_CONTAINER_NAME_CONFIGAPP}
      - EUREKA_HOST=${SERVER_CONTAINER_NAME_DISCOVERYSERVER}
      - DB_HOST=${DB_CONTAINER_NAME_STUDENT}
      - CLASSROOM_MS=${API_CONTAINER_NAME_CLASSROOM}
      - USER_MS=${API_CONTAINER_NAME_USER}
      - PORT=${API_INTERNAL_PORT}
    ports:
      - "${API_EXTERNAL_PORT_STUDENT}:${API_INTERNAL_PORT}"
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
      configapp:
        condition: service_started
      postgres-student:
        condition: service_started
    networks:
      - ism

  user:
    container_name: ${API_CONTAINER_NAME_USER}
    build:
      context: user
      dockerfile: Dockerfile.user
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_HOST=${SERVER_CONTAINER_NAME_CONFIGAPP}
      - EUREKA_HOST=${SERVER_CONTAINER_NAME_DISCOVERYSERVER}
      - DB_HOST=${DB_CONTAINER_NAME_USER}
      - PORT=${API_INTERNAL_PORT}
    ports:
      - "${API_EXTERNAL_PORT_USER}:${API_INTERNAL_PORT}"
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
      configapp:
        condition: service_started
      postgres-user:
        condition: service_started
    networks:
      - ism

  classroom:
    container_name: ${API_CONTAINER_NAME_CLASSROOM}
    build:
      context: classroom
      dockerfile: Dockerfile.classroom
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_HOST=${SERVER_CONTAINER_NAME_CONFIGAPP}
      - EUREKA_HOST=${SERVER_CONTAINER_NAME_DISCOVERYSERVER}
      - DB_HOST=${DB_CONTAINER_NAME_CLASSROOM}
      - STUDENT_MS=${API_CONTAINER_NAME_STUDENT}
      - USER_MS=${API_CONTAINER_NAME_USER}
      - PORT=${API_INTERNAL_PORT}
    ports:
      - "${API_EXTERNAL_PORT_CLASSROOM}:${API_INTERNAL_PORT}"
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
      configapp:
        condition: service_started
      postgres-classroom:
        condition: service_started
    networks:
      - ism
networks:
  ism:
    external: true

