services:
  postgres-classroom:
    image: postgres:14.1-alpine
    container_name: ${DB_CONTAINER_NAME_CLASSROOM}
    hostname: postgres-classroom
    environment:
      - POSTGRES_DB=${CLASSROOM_DB_NAME}
      - POSTGRES_USER=${CLASSROOM_DB_USER}
      - POSTGRES_PASSWORD=${CLASSROOM_DB_PASS}
    ports:
      - "${CLASSROOM_DB_LOCAL_PORT}:5432"
    volumes:
      - ./.docker/pg_classroom_data:/var/lib/postgresql/data
      - ./.docker/schema/classroom:/docker-entrypoint-initdb.d
    networks:
      - ism

  # postgres-teacher:
  #   image: postgres:14.1-alpine
  #   container_name: ${DB_CONTAINER_NAME_TEACHER}
  #   hostname: postgres-teacher
  #   environment:
  #     - POSTGRES_DB=${TEACHER_DB_NAME}
  #     - POSTGRES_USER=${TEACHER_DB_USER}
  #     - POSTGRES_PASSWORD=${TEACHER_DB_PASS}
  #   ports:
  #     - "${TEACHER_DB_LOCAL_PORT}:5432"
  #   volumes:
  #     - ./.docker/pg_teacher_data:/var/lib/postgresql/data
  #   networks:
  #     - ism

  postgres-student:
    image: postgres:14.1-alpine
    container_name: ${DB_CONTAINER_NAME_STUDENT}
    hostname: postgres-student
    environment:
      - POSTGRES_DB=${STUDENT_DB_NAME}
      - POSTGRES_USER=${STUDENT_DB_USER}
      - POSTGRES_PASSWORD=${STUDENT_DB_PASS}
    ports:
      - "${STUDENT_DB_LOCAL_PORT}:5432"
    volumes:
      - ./.docker/pg_student_data:/var/lib/postgresql/data
      - ./.docker/schema/student:/docker-entrypoint-initdb.d
    networks:
      - ism

  # postgres-exams:
  #   image: postgres:14.1-alpine
  #   container_name: ${DB_CONTAINER_NAME_EXAMS}
  #   hostname: postgres-exams
  #   environment:
  #     - POSTGRES_DB=${EXAMS_DB_NAME}
  #     - POSTGRES_USER=${EXAMS_DB_USER}
  #     - POSTGRES_PASSWORD=${EXAMS_DB_PASS}
  #   ports:
  #     - "${EXAMS_DB_LOCAL_PORT}:5432"
  #   volumes:
  #     - ./.docker/pg_exams_data:/var/lib/postgresql/data
  #   networks:
  #     - ism

networks:
  ism:
    external: true
