services:
  student:
    container_name: student
    build:
      context: student
      dockerfile: Dockerfile.student
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_HOST=${SERVER_CONTAINER_NAME_CONFIGAPP}
      - EUREKA_HOST=${SERVER_CONTAINER_NAME_DISCOVERYSERVER}
      - DB_HOST=${DB_CONTAINER_NAME_STUDENT}
      - CLASSROOM_MS=${API_CONTAINER_NAME_CLASSROOM}
      - TEACHER_MS=${API_CONTAINER_NAME_TEACHER}
      - PORT=${API_INTERNAL_PORT}
    ports:
      - "${API_EXTERNAL_PORT_STUDENT}:${API_INTERNAL_PORT}"
    restart: on-failure
    depends_on:
      eureka:
        condition: service_started
      configapp:
        condition: service_started
      postgres-student:
        condition: service_started
    networks:
      - ism
networks:
  ism:
    external: true

